services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./tasks.db
    volumes:
      - sqlite_data:/app/backups
      - sqlite_db:/app/tasks.db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    restart: always

volumes:
  sqlite_data:
  sqlite_db:
